package gov.ic.geoint.spreadsheet.diff.swing;

import gov.ic.geoint.spreadsheet.diff.AppendDiffToWorkbookListener;
import gov.ic.geoint.spreadsheet.diff.DiffListener;
import gov.ic.geoint.spreadsheet.diff.RowChangeDiff;
import gov.ic.geoint.spreadsheet.excel.ExcelWorkbook;
import java.awt.Desktop;
import java.io.File;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class CompareFrame extends javax.swing.JFrame {

    private File baseFile;
    private File compareFile;
    private final static Logger logger = Logger.getLogger(CompareFrame.class.getName());

    /**
     * Creates new form CompareFrame
     */
    public CompareFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        baseFileButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newFileButton = new javax.swing.JButton();
        compareButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Base File:");

        baseFileButton.setText("Find...");
        baseFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseFileButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("New File:");

        newFileButton.setText("Find...");
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });

        compareButton.setText("Compare");
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Excel Compare Tool");

        jLabel4.setText("GETS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(baseFileButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(newFileButton))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(compareButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(baseFileButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(compareButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baseFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseFileButtonActionPerformed
        if (evt.getSource() == baseFileButton) {
            final JFileChooser fc = new JFileChooser();
            int returnVal = fc.showOpenDialog(this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File chosenFile = fc.getSelectedFile();
                if (!chosenFile.exists()) {
                    JOptionPane.showMessageDialog(this, "File does not exist!");
                }
                if (!chosenFile.canRead()) {
                    JOptionPane.showMessageDialog(this, "Cannot read file.");
                }
                baseFile = chosenFile;
                baseFileButton.setText(baseFile.getName());
            }
        }
    }//GEN-LAST:event_baseFileButtonActionPerformed

    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        if (evt.getSource() == newFileButton) {
            final JFileChooser fc = new JFileChooser((baseFile != null) ? baseFile.getParent() : "");
            int returnVal = fc.showOpenDialog(this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File chosenFile = fc.getSelectedFile();
                if (!chosenFile.exists()) {
                    JOptionPane.showMessageDialog(this, "File does not exist!");
                }
                if (!chosenFile.canRead()) {
                    JOptionPane.showMessageDialog(this, "Cannot read file.");
                }
                compareFile = chosenFile;
                newFileButton.setText(compareFile.getName());
            }
        }
    }//GEN-LAST:event_newFileButtonActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        if (compareFile == null) {
            JOptionPane.showMessageDialog(this, "Compare file hasn't been set.");
            return;
        }
        if (baseFile == null) {
            JOptionPane.showMessageDialog(this, "Base file has not been set.");
        }

        compareButton.setEnabled(false);

        try {
            File tmpFile = doCompare();
            Desktop.getDesktop().open(tmpFile);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to open diff file!");
            logger.log(Level.SEVERE, "Problems comparing file", ex);
        }
        compareButton.setEnabled(true);

    }//GEN-LAST:event_compareButtonActionPerformed

    private File doCompare() throws InterruptedException {
        //todo make diff type configurable
        //todo make file type configurable
        RowChangeDiff diff = new RowChangeDiff(new ExcelWorkbook(baseFile),
                new ExcelWorkbook(compareFile));
        File tmpFile = new File(System.getProperty("java.io.tmpdir") + "/diff_" + UUID.randomUUID().toString());
        tmpFile.deleteOnExit();
        DiffListener output = new AppendDiffToWorkbookListener(new ExcelWorkbook(tmpFile));
        diff.addListener(output);
        diff.diff();
        return tmpFile;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompareFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baseFileButton;
    private javax.swing.JButton compareButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton newFileButton;
    // End of variables declaration//GEN-END:variables
}
